const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const context={window:{}};vm.createContext(context);
for(const file of ['complementarios-catalogo.js','requisitoriados-catalogo.js','prostitucion-catalogo.js','victimas-catalogo.js','menores-catalogo.js','materiales-catalogo.js','vehiculos-catalogo.js','consulta-modelo.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
const m=context.window.ConsultaModelo,cats=m.categories(),drug=cats.find(c=>c.id==='drogas');
const parents=new Map([['op-a',{id:'op-a',fecha:'2026-09-15',unidad:'A',departamento:'LIMA',nota_sicpip:'NI-001'}],['op-b',{id:'op-b',fecha:'2026-08-10',unidad:'B',departamento:'CUSCO'}]]);
const rows=[m.normalize({id:'1',intervencion_id:'op-a',tipo:'kg_pbc',cantidad:1.5},drug,parents),m.normalize({id:'2',intervencion_id:'op-a',tipo:'env_pbc',cantidad:100},drug,parents),m.normalize({id:'3',intervencion_id:'op-b',tipo:'kg_cc',cantidad:2},drug,parents)];
test('Prostitución: género, documentos con ceros y filtros por operativo',()=>{const c=cats.find(c=>c.id==='prostitucion'),rows=[m.normalize({id:'p1',intervencion_id:'op-a',datos:{genero:'FEMENINO',numero_documento:'00123456'}},c,parents),m.normalize({id:'p2',intervencion_id:'op-b',datos:{genero:'MASCULINO'}},c,parents),m.normalize({id:'p3',intervencion_id:'op-a',datos:{}},c,parents)];const totals=Object.fromEntries(m.metrics(rows,c));assert.equal(totals.Femenino,1);assert.equal(totals.Masculino,1);assert.equal(totals['Género sin registrar'],1);assert.equal(totals['Operativos vinculados'],2);assert.equal(m.filter(rows,{unit:'A',search:'NI-001',field:'numero_documento',value:'00123456'}).length,1);assert.equal(rows[0].data.numero_documento,'00123456');assert.equal(c.table,'intervencion_prostitucion');});
test('Víctimas: indicadores de edad del formato actualizado',()=>{const c=cats.find(c=>c.id==='victimas'),rows=[{data:{edad:0}},{data:{edad:17}},{data:{edad:18}},{data:{edad:null}}];const totals=Object.fromEntries(m.metrics(rows,c));assert.equal(totals['Menores de edad'],2);assert.equal(totals['Mayores de edad'],1);assert.equal(totals.Registros,4);assert.ok(!c.fields.some(f=>f.key==='nombres'));});
test('Cantidades separadas y operativo contado una sola vez',()=>{const metrics=Object.fromEntries(m.metrics(rows,drug));assert.equal(metrics['Cantidad (kg)'],3.5);assert.equal(metrics['Cantidad (envoltorios)'],100);assert.equal(metrics['Operativos vinculados'],2);});
test('Filtros combinados, fechas inclusivas, NI y campo específico',()=>{assert.equal(m.filter(rows,{unit:'A',from:'2026-09-15',to:'2026-09-15',search:'ni-001',field:'medida',value:'kg'}).length,1);assert.equal(m.filter(rows,{place:'cusco'}).length,1);});
test('RQ usa su propia fecha y datos; detenido histórico sigue consultable',()=>{const rq=m.normalize({id:'r',intervencion_id:'op-a',datos:{fecha:'2026-09-16',apellido_paterno:'PÉREZ'}},cats.find(c=>c.id==='rq'),parents);assert.equal(rq.date,'2026-09-16');assert.equal(m.filter([rq],{search:'perez'}).length,1);const old=m.normalize({id:'old',fecha:'2020-01-01',unidad:'A',personas:{nombres:'Ana'}},cats.find(c=>c.id==='detenidos'),parents);assert.equal(old.parentId,null);assert.equal(old.data.nombre,'Ana');});
test('Paginación de más de 1000 resultados, sin truncamiento por límite API',async()=>{const all=Array.from({length:1007},(_,n)=>({id:String(n).padStart(6,'0')}));let calls=0;const client={from(){let cursor='';return{select(){return this;},order(){return this;},limit(){return this;},gt(k,v){cursor=v;return this;},then(resolve){calls++;resolve({data:all.filter(r=>r.id>cursor).slice(0,500)});}};}};assert.equal((await m.readAll(client,{table:'test'})).length,1007);assert.equal(calls,4);});
test('Errores y cambio de sesión impiden presentar resultados parciales',async()=>{await assert.rejects(m.readAll({from(){return {select(){return this;},order(){return this;},limit(){return Promise.resolve({error:new Error('sin permiso')});}};}},{table:'x'}),/sin permiso/);await assert.rejects(m.readAll({},drug,()=>false),/cancelada/);});

test('Nuevas categorías: monedas separadas, cantidades y documento como texto',()=>{assert.equal(cats.find(c=>c.id==='prostitucion').title,'Proxenetismo');for(const id of ['dinero','celulares','chips','migraciones','personas_ubicadas','expulsados'])assert.equal(cats.find(c=>c.id===id).table,'intervencion_complementarios');const money=cats.find(c=>c.id==='dinero');const data=[m.normalize({id:'d1',intervencion_id:'op-a',datos:{soles:0.10,dolares:2}},money,parents),m.normalize({id:'d2',intervencion_id:'op-a',datos:{soles:0.20,euros:3}},money,parents)];const out=Object.fromEntries(m.metrics(data,money));assert.equal(out['Soles (S/)'],0.3);assert.equal(out['Dólares (USD)'],2);assert.equal(out['Euros (EUR)'],3);const chips=cats.find(c=>c.id==='chips');assert.equal(Object.fromEntries(m.metrics([{data:{cantidad:3},parentId:'a',unit:'A'},{data:{cantidad:2},parentId:'a',unit:'A'}],chips))['Cantidad total'],5);});
