const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),assert=require('node:assert/strict');
const db=new PGlite();const a='00000000-0000-0000-0000-000000000001',op='00000000-0000-0000-0000-000000000002',child='00000000-0000-0000-0000-000000000003';
(async()=>{try{
await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select '${a}'::uuid$$;create table perfiles(id uuid,rol text,activo boolean);insert into perfiles values('${a}','administrador',true);create function puede_editar_unidad(text) returns boolean language sql as $$select $1='UNIDAD'$$;create table intervenciones(id uuid primary key,tipo text,unidad text);alter table intervenciones enable row level security;create table produccion_historica(id uuid primary key,tabla text,tipo text,unidad text,operativo_id uuid);create table detenciones(id uuid primary key,intervencion_id uuid references intervenciones on delete restrict);create table detencion_archivos(id uuid,detencion_id uuid references detenciones);create table intervencion_grupos(id uuid primary key,intervencion_id uuid references intervenciones);create table intervencion_grupo_integrantes(id uuid,grupo_id uuid references intervencion_grupos,detencion_id uuid references detenciones);create table intervencion_operativos(intervencion_id uuid references intervenciones);create table intervencion_materiales(id uuid,intervencion_id uuid references intervenciones);create table detencion_delitos(id uuid,detencion_id uuid references detenciones);`);
await db.exec(fs.readFileSync(require('path').join(__dirname,'../backend/supabase/migrations/202609260001_eliminar_operativo.sql'),'utf8'));
await db.exec(`insert into intervenciones values('${op}','operativo','UNIDAD');insert into detenciones values('${child}','${op}');insert into intervencion_operativos values('${op}');insert into detencion_delitos values('${a}','${child}');`);
const call=async(confirm=false,signature=null,historical=false)=> (await db.query('select eliminar_operativo_controlado($1,$2,$3,$4,$5) r',[op,historical,confirm,signature,'Registro de prueba'])).rows[0].r;
const preview=await call();assert.equal(preview.conteos.detenciones,1);assert.equal((await db.query('select count(*) n from intervenciones')).rows[0].n,1);
await db.exec("update perfiles set rol='estadistico_jefatura'");await assert.rejects(call());await db.exec("update perfiles set rol='estadistico_direccion'");
await assert.rejects(call(true,'stale'));assert.equal((await db.query('select count(*) n from detenciones')).rows[0].n,1);
await db.exec(`insert into detencion_archivos values('${a}','${child}')`);await assert.rejects(call());await db.exec('delete from detencion_archivos');
const p=await call();assert.equal((await call(true,p.firma)).eliminado,true);assert.equal((await db.query('select count(*) n from intervenciones')).rows[0].n,0);assert.equal((await db.query('select count(*) n from detenciones')).rows[0].n,0);assert.equal((await db.query('select count(*) n from operativos_eliminados_auditoria')).rows[0].n,1);
await db.exec(`insert into produccion_historica values('${op}','intervenciones','operativo','UNIDAD',null),('${child}','detenciones',null,'UNIDAD','${op}')`);const h=await call(false,null,true);await call(true,h.firma,true);assert.equal((await db.query('select count(*) n from produccion_historica')).rows[0].n,0);
await db.exec("update perfiles set activo=false");await assert.rejects(call());console.log('PASS: vista previa no borra; solo administrador/dirección; versión obsoleta rechazada; archivos protegidos; hijos eliminados sin huérfanos; histórico y auditoría; inactivos bloqueados.');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
