const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),db=new PGlite();
const read=n=>fs.readFileSync(path.join(root,'backend/supabase/migrations',n),'utf8');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{
 const schema=JSON.parse(fs.readFileSync(path.join(root,'datos/estructura-detallado-v1.json'),'utf8'));
 const map=JSON.parse(fs.readFileSync(path.join(root,'datos/mapeo-grupos-v1.json'),'utf8'));
 for(const t of map.tipos)assert.deepEqual(Object.keys(t.columnas),schema.hojas.find(h=>h.nombre===t.hoja).campos.map(c=>c.columna));
 await db.exec(`create role authenticated;create role anon;create schema auth;
 create table perfiles(id uuid primary key,rol text,activo boolean,unidad text,departamento text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function usuario_activo() returns boolean language sql stable security definer set search_path=public as $$select coalesce((select activo from perfiles where id=auth.uid()),false)$$;
 create function es_administrador() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from perfiles where id=auth.uid() and activo and rol='administrador')$$;
 create function unidad_actual() returns text language sql stable security definer set search_path=public as $$select unidad from perfiles where id=auth.uid()$$;
 create function puede_acceder_unidad(u text) returns boolean language sql stable security definer set search_path=public as $$select usuario_activo() and (es_administrador() or unidad_actual()=u)$$;
 grant usage on schema auth to authenticated;grant select on perfiles to authenticated;
 create table detenciones(id uuid primary key,intervencion_id uuid,integra_organizacion boolean,tipo_organizacion text);
 grant select,update,delete on detenciones to authenticated;`);
 for(const [n,rol,active,u]of [[1,'operador',true,'A'],[2,'operador',true,'B'],[3,'administrador',true,'C'],[4,'operador',false,'A'],[5,'supervisor',true,'A']])await db.query('insert into perfiles values($1,$2,$3,$4,$5)',[id(n),rol,active,u,'LIMA']);
 await db.exec(read('202609150002_base_intervenciones.sql'));
 await db.exec("alter table intervenciones add column resultados_previstos text[] not null default '{}'");
 const migration=read('202609150009_grupos_operativo.sql');await db.exec(migration);
 async function actor(n){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role authenticated');}
 const member=(n,rol='Integrante')=>({detencion_id:id(n),rol});
 const save=async(n=200,v=0,t='banda',ms=[member(10)],parent=100,name='GRUPO FICTICIO')=>(await db.query('select guardar_grupo_operativo($1,$2,$3,$4,$5,$6,$7,$8) r',[id(n),id(parent),v,t,name,'MODALIDAD FICTICIA','REFERENCIA FICTICIA',JSON.stringify(ms)])).rows[0].r;
 await actor(1);await db.query("insert into intervenciones(id,tipo,fecha) values($1,'operativo','2026-09-15')",[id(100)]);
 await db.query("insert into intervenciones(id,tipo) values($1,'operativo')",[id(101)]);
 await db.exec('reset role');
 for(const [n,parent,t]of [[10,100,'banda'],[11,100,'banda'],[12,100,'organizacion'],[13,101,'banda'],[14,100,null]])await db.query('insert into detenciones values($1,$2,true,$3)',[id(n),id(parent),t]);
 await actor(1);
 const first=await save();assert.deepEqual(await save(),first);
 await assert.rejects(save(200,0,'banda',[member(11)]));
 for(const ms of [[],[member(10),member(10)],[member(13)],[member(12)],[member(14)],[member(11,'')],[{...member(11),extra:'x'}]])await assert.rejects(save(201,0,'banda',ms,100,'OTRO'));
 await assert.rejects(save(201,0,'banda',[member(10)],100,'OTRO'));
 await assert.rejects(save(201,0,'banda',[member(11)],100,' grupo ficticio '));
 const updated=await save(200,1,'banda',[member(10,'Cabecilla'),member(11)]);assert.equal(updated.version,2);assert.deepEqual(await save(200,1,'banda',[member(11),member(10,'Cabecilla')]),updated);
 assert.equal((await db.query('select count(*)::int n from intervencion_grupo_integrantes')).rows[0].n,2);
 await assert.rejects(save(200,2,'organizacion',[member(12)]));
 await save(202,0,'organizacion',[member(12,'Coordinador')],100,'ORGANIZACION FICTICIA');
 await assert.rejects(db.exec("update intervenciones set resultados_previstos='{}'"));
 await assert.rejects(db.query("update detenciones set tipo_organizacion='organizacion' where id=$1",[id(10)]));
 await assert.rejects(db.query('delete from detenciones where id=$1',[id(10)]));
 await assert.rejects(db.exec('delete from intervencion_grupo_integrantes'));
 await assert.rejects(db.exec("update intervencion_grupos set nombre='CAMBIO DIRECTO'"));
 const before=(await db.query('select * from intervencion_grupos order by id')).rows;
 await assert.rejects(save(200,2,'banda',[member(13)]));assert.deepEqual((await db.query('select * from intervencion_grupos order by id')).rows,before);
 await actor(2);assert.equal((await db.query('select * from intervencion_grupos')).rows.length,0);assert.equal((await db.query('select * from intervencion_grupo_integrantes')).rows.length,0);await assert.rejects(save(200,2));
 await actor(5);assert.equal((await db.query('select * from intervencion_grupos')).rows.length,2);await assert.rejects(save(200,2));
 await actor(4);assert.equal((await db.query('select * from intervencion_grupos')).rows.length,0);await assert.rejects(save(200,2));
 await actor(null);await assert.rejects(save(200,2));
 await actor(3);await save(200,2,'banda',[member(11)]);
 await actor(1);await save(203,0,'banda',[member(10)],100,'SEGUNDO GRUPO');
 await db.exec('reset role');await db.exec(migration);
 assert.equal((await db.query('select count(*)::int n from intervencion_grupos')).rows[0].n,3);
 console.log('OK: mapeo 40/41 columnas, alta, edición, reintentos, duplicados, ámbito, clasificación, vínculos, RLS, permisos y reaplicación.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.close());
