// Fictional records only; reusable in unit and browser export tests.
function fixture(){
 const parent={id:'op-a',tipo:'operativo',version:1,fecha:'2026-09-23',hora:'09:30:00',unidad:'UNIDAD A',departamento:'LIMA',provincia:'LIMA',distrito:'LINCE',direccion_policial:'DIRNIC',direccion_especializada_region:'DIRITPTIM',division_policial:'DIVISIÓN FICTICIA',departamento_policial:'DPTO FICTICIO',unidad_area_equipo:'UNIDAD A',nota_sicpip:'0000123',latitud:-12.08,longitud:-77.03,intervencion_operativos:{resultado:'positivo',personal_cargo:0,control_identidad_extranjeros:'CONTROL FICTICIO',intervencion_penales:'NO'}};
 const d={id:'det-1',codigo:'DET-FICTICIO',intervencion_id:'op-a',fecha:'2026-09-23',hora:'09:30',personas:{apellido_paterno:'PRUEBA',apellido_materno:'FICTICIA',nombres:'PERSONA',edad:25,genero:'FEMENINO',nacionalidad:'PERU',tipo_documento:'DNI',numero_documento:'00123456'},es_funcionario_publico:false,tipo_organizacion:'banda',integra_organizacion:true,nombre_organizacion:'BANDA FICTICIA',situacion_actual:'DETENIDO',detencion_delitos:[{orden:2,es_tentativa:false,delito_general:'DELITO DOS'},{orden:1,es_tentativa:true,delito_general:'DELITO UNO'}],detencion_armas:[]};
 const data={intervenciones:[parent,{...parent,id:'op-b',unidad:'UNIDAD B',tipo:'megaoperativo',fecha:'2026-08-01'}],detenciones_reportables:[d,{...d,id:'det-2'}],detenciones:[d,{...d,id:'det-2'},{...d,id:'det-3'}],intervencion_grupos:[{id:'banda-1',intervencion_id:'op-a',tipo:'banda',nombre:'BANDA FICTICIA',modalidad:'FICTICIA',intervencion_grupo_integrantes:[{grupo_id:'banda-1',detencion_id:'det-2',rol:'INTEGRANTE'},{grupo_id:'banda-1',detencion_id:'det-1',rol:'INTEGRANTE'}]},{id:'oocc-1',intervencion_id:'op-a',tipo:'organizacion',nombre:'ORGANIZACIÓN FICTICIA',modalidad:'FICTICIA',intervencion_grupo_integrantes:[{grupo_id:'oocc-1',detencion_id:'det-3',rol:'INTEGRANTE'}]}]};
 data.intervencion_requisitoriados=[{id:'rq-1',intervencion_id:'op-a',datos:{fecha:'2026-09-24',hora:'10:00',nombres:'RQ FICTICIO',numero_documento:'00000111',edad:30}}];
 data.intervencion_menores=[{id:'menor-1',intervencion_id:'op-a',datos:{fecha:'2026-09-23',nombres:'MENOR FICTICIO',edad:15}}];
 data.intervencion_drogas=['env_pbc','env_cc','env_marihuana','kg_pbc'].map((tipo,i)=>({id:'droga-'+i,intervencion_id:'op-a',tipo,cantidad:i+1}));
 data.intervencion_materiales=['fuego','blanca','municion'].map((tipo,i)=>({id:'arma-'+i,intervencion_id:'op-a',tipo,datos:{tipo:'FICTICIO',serie:'00001',cantidad:100,situacion:'INCAUTADO'}}));
 data.intervencion_vehiculos=['mayor','menor'].map((tipo,i)=>({id:'veh-'+i,intervencion_id:'op-a',tipo,datos:{placa:'ABC-001',marca:'FICTICIA',situacion:'INCAUTADO',valorizacion:0}}));
 data.intervencion_prostitucion=[{id:'prox-1',intervencion_id:'op-a',tipo:'prostitucion',datos:{fecha:'2026-09-23',edad:25,genero:'FEMENINO',nacionalidad:'PERU',nombres:'HISTÓRICO NO EXPORTABLE'}}];
 data.intervencion_victimas=[{id:'vict-1',intervencion_id:'op-a',tipo:'victima',datos:{fecha:'2026-09-23',edad:0,genero:'FEMENINO',nacionalidad:'PERU',nombres:'HISTÓRICO NO EXPORTABLE'}}];
 data.intervencion_complementarios=[['dinero',{soles:123.45,dolares:67.89,euros:0,dinero_otro:'10 moneda ficticia'}],['celulares',{cantidad:1,imei_fisico:'000123456789012',imei_logico:'001234567890123',observaciones:'=HYPERLINK("https://example.invalid")'}],['chips',{cantidad:5,tipo_chip:'SIM'}],['migraciones',{edad:20,numero_documento:'000099',ley_migraciones:'LEY FICTICIA'}],['personas_ubicadas',{edad:17,condicion_edad:'MENOR',lugar_ubicacion:'LUGAR FICTICIO'}],['expulsados',{edad:40,condicion:'FICTICIA'}]].map(([tipo,datos],i)=>({id:'comp-'+i,intervencion_id:'op-a',tipo,datos:{fecha:'2026-09-23',...datos}}));
 return data;
}
module.exports=fixture;
