const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),db=new PGlite();
const read=n=>fs.readFileSync(path.join(root,'backend/supabase/migrations',n),'utf8');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{
 const schema=JSON.parse(fs.readFileSync(path.join(root,'datos/estructura-detallado-v1.json'),'utf8'));
 const map=JSON.parse(fs.readFileSync(path.join(root,'datos/mapeo-requisitoriados-v1.json'),'utf8'));
 assert.equal(Object.keys(map.columnas).length,38);assert.deepEqual(Object.keys(map.columnas),schema.hojas.find(h=>h.nombre===map.hoja).campos.map(c=>c.columna));
 assert.deepEqual(map.catalogos.tipo.valores,['ORDEN DE CAPTURA','RQ INTERNACIONAL']);
 await db.exec(`create role authenticated;create role anon;create schema auth;
 create table perfiles(id uuid primary key,rol text,activo boolean,unidad text,departamento text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function usuario_activo() returns boolean language sql stable security definer set search_path=public as $$select coalesce((select activo from perfiles where id=auth.uid()),false)$$;
 create function es_administrador() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from perfiles where id=auth.uid() and activo and rol='administrador')$$;
 create function unidad_actual() returns text language sql stable security definer set search_path=public as $$select unidad from perfiles where id=auth.uid()$$;
 create function puede_acceder_unidad(u text) returns boolean language sql stable security definer set search_path=public as $$select usuario_activo() and (es_administrador() or unidad_actual()=u)$$;
 grant usage on schema auth to authenticated;grant select on perfiles to authenticated;
 create table detenciones(id uuid primary key,intervencion_id uuid);
 grant select,delete on detenciones to authenticated;`);
 for(const [n,rol,active,u]of [[1,'operador',true,'A'],[2,'operador',true,'B'],[3,'administrador',true,'C'],[4,'operador',false,'A'],[5,'supervisor',true,'A']])await db.query('insert into perfiles values($1,$2,$3,$4,$5)',[id(n),rol,active,u,'LIMA']);
 await db.exec(read('202609150002_base_intervenciones.sql'));
 await db.exec("alter table intervenciones add column resultados_previstos text[] not null default '{}'");
 const migration=read('202609150010_requisitoriados_operativo.sql');await db.exec(migration);
 async function actor(n){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role authenticated');}

 await db.exec('reset role');
 await db.exec(`alter table detenciones add column persona_id uuid,add column fecha date,add column hora time,add column es_funcionario_publico boolean,add column entidad_publica text,add column detalle_entidad_publica text;
 create table personas(id uuid primary key,apellido_paterno text,apellido_materno text,nombres text,edad int,genero text,nacionalidad text,tipo_documento text,numero_documento text);
 create table detencion_delitos(id uuid,detencion_id uuid,orden int,es_tentativa boolean,fuero_ley_especial text,delito_general text,delito_especifico text,subtipo text);
 alter table detenciones enable row level security;create policy d_read on detenciones for select to authenticated using(exists(select 1 from intervenciones i where i.id=intervencion_id));
 grant select on personas,detencion_delitos to authenticated;`);
 await actor(1);await db.query("insert into intervenciones(id,tipo,fecha,nota_sicpip,resultados_previstos) values($1,'operativo','2026-09-15','NI PRINCIPAL','{detenidos}')",[id(100)]);
 await db.exec('reset role');
 await db.query("insert into personas(id,apellido_paterno,nombres,edad) values($1,'FICTICIO','ORIGEN',30)",[id(9)]);
 await db.query("insert into detenciones(id,intervencion_id,persona_id,fecha) values($1,$2,$3,'2026-09-15'),($4,$2,$3,'2026-09-15')",[id(10),id(100),id(9),id(11)]);
 await actor(1);await db.query("select guardar_requisitoriado_operativo($1,$2,$3,0,'ORDEN DE CAPTURA',false)",[id(200),id(100),id(10)]);
 await db.exec('reset role');
 const rqMigration=read('202609160012_requisitoriados_independientes.sql'),niMigration=read('202609160013_ampliaciones_ni.sql');
 await db.exec(rqMigration);await db.exec(niMigration);
 await actor(1);
 assert.equal((await db.query('select count(*)::int n from detenciones')).rows[0].n,2,'preserva historial');
 assert.equal((await db.query('select count(*)::int n from detenciones_reportables')).rows[0].n,1,'solo excluye origen RQ');
 assert.equal((await db.query('select datos from intervencion_requisitoriados')).rows[0].datos.nombres,'ORIGEN');
 await assert.rejects(db.query("select guardar_requisitoriado_operativo($1,$2,$3,0,'ORDEN DE CAPTURA',false)",[id(201),id(100),id(11)]));
 const valid={apellido_paterno:'FICTICIO',nombres:'SOLO RQ',fecha:'2026-09-15',edad:30,tipo:'ORDEN DE CAPTURA',mas_buscado:'No',es_funcionario:'No',tipo_documento:'DNI',numero_documento:'TEST-100'};
 const rqsave=async(n,v=0,data=valid,parent=100)=>(await db.query('select guardar_requisitoriado_independiente($1,$2,$3,$4,$5) r',[id(n),id(parent),v,data.tipo,JSON.stringify(data)])).rows[0].r;
 const one=await rqsave(201);assert.deepEqual(await rqsave(201),one);assert.equal((await db.query('select count(*)::int n from detenciones')).rows[0].n,2);
 await assert.rejects(rqsave(202),/duplicate/i);
 for(const patch of [{edad:-1},{edad:3.5},{entidad_publica:'No corresponde'},{tipo:'OTRO'},{mas_buscado:null},{fecha:'2026-02-30'}])await assert.rejects(rqsave(202,0,{...valid,...patch}));
 const edit={...valid,tipo:'RQ INTERNACIONAL',mas_buscado:'Sí'};const two=await rqsave(201,1,edit);assert.equal(two.version,2);assert.deepEqual(await rqsave(201,1,edit),two);await assert.rejects(rqsave(201,1,valid));
 assert.equal((await db.query('select detencion_id from intervencion_requisitoriados where id=$1',[id(201)])).rows[0].detencion_id,null);
 await assert.rejects(db.query('update intervencion_requisitoriados set detencion_id=$1 where id=$2',[id(11),id(201)]));
 const note={numero:'NI AMPLIACION 1',fecha:'2026-09-16',hora:'12:30',detalle:'Se encontró un celular adicional.'};
 const nisave=async(n,v=0,data=note,parent=100)=>(await db.query('select guardar_ampliacion_operativo($1,$2,$3,$4,$5) r',[id(n),id(parent),v,'ampliacion',JSON.stringify(data)])).rows[0].r;
 const n1=await nisave(300);assert.deepEqual(await nisave(300),n1);await assert.rejects(nisave(301));
 await assert.rejects(nisave(301,0,{...note,numero:' ni ampliacion 1 '}));await assert.rejects(nisave(301,0,{...note,numero:'ni principal'}));
 for(const patch of [{detalle:''},{fecha:'abc'},{hora:'24:30'},{oculto:'x'}])await assert.rejects(nisave(301,0,{...note,numero:'NI 2',...patch}));
 await nisave(301,0,{...note,numero:'NI AMPLIACION 2'});
 const revised={...note,detalle:'Hallazgo adicional documentado.'};const n2=await nisave(300,1,revised);assert.deepEqual(await nisave(300,1,revised),n2);await assert.rejects(nisave(300,1,note));
 assert.equal((await db.query('select count(*)::int n from intervenciones')).rows[0].n,1);
 assert.equal((await db.query('select nota_sicpip from intervenciones')).rows[0].nota_sicpip,'NI PRINCIPAL');
 await assert.rejects(db.exec("update intervenciones set nota_sicpip=null"));await assert.rejects(db.exec("update intervenciones set nota_sicpip='NI AMPLIACION 1'"));
 for(const who of [2,4,5]){await actor(who);await assert.rejects(rqsave(202));await assert.rejects(nisave(302));assert.equal((await db.query('select * from intervencion_notas')).rows.length,who===5?2:0);assert.equal((await db.query('select * from detenciones_reportables')).rows.length,who===5?1:0);}
 await actor(3);await rqsave(201,2,valid);await nisave(300,2,note);await assert.rejects(db.exec('delete from intervencion_notas'));
 await db.query("insert into intervenciones(id,tipo,fecha) values($1,'operativo','2026-09-16')",[id(101)]);await assert.rejects(nisave(302,0,note,101));
 await assert.rejects(db.query('update intervencion_notas set intervencion_id=$1 where id=$2',[id(101),id(300)]));
 await db.exec('reset role');await db.exec(rqMigration);await db.exec(niMigration);await db.exec('set role anon');await assert.rejects(db.exec('select * from detenciones_reportables'));await assert.rejects(db.exec('select * from intervencion_notas'));
 console.log('OK: migración RQ sin pérdidas, conteos separados, RQ sin detenido, 38 columnas, alta/edición y reintentos; múltiples NI, duplicados, nota principal intacta, versiones y permisos.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.close());
