begin;
alter table public.intervencion_complementarios drop constraint intervencion_complementarios_tipo_check;
alter table public.intervencion_complementarios add constraint intervencion_complementarios_tipo_check check(tipo in ('dinero','celulares','migraciones','chips','personas_ubicadas','expulsados','locales'));
alter table public.intervenciones drop constraint resultados_previstos_validos;
alter table public.intervenciones add constraint resultados_previstos_validos check(resultados_previstos <@ array['detenidos','requisitoriados','menores','victimas','prostitucion','dinero','celulares','migraciones','chips','expulsados','bienes','bandas','organizaciones','armas','drogas','vehiculos','personas_ubicadas','otros','locales']::text[] and array_position(resultados_previstos,null) is null);
do $patch$ declare d text; begin
 select pg_get_functiondef('public.proteger_complementarios_operativo()'::regprocedure) into d;
 if position('if spec is null then' in d)=0 then raise exception 'Validador de complementarios incompatible';end if;
 d:=replace(d,'if spec is null then', $inject$if new.tipo='locales' then spec:=$local$[{"key": "fecha", "label": "Fecha", "type": "date", "required": true, "group": "registro"}, {"key": "hora", "label": "Hora", "type": "time", "required": false, "group": "registro"}, {"key": "situacion", "label": "Situación del inmueble", "type": "text", "required": true, "group": "registro"}, {"key": "tipo_inmueble", "label": "Tipo de inmueble", "type": "text", "required": true, "group": "registro"}, {"key": "detalle_inmueble", "label": "Detalle del inmueble", "type": "text", "required": true, "group": "registro"}, {"key": "valorizacion", "label": "Valorización del inmueble incautado (S/)", "type": "number", "required": false, "group": "registro", "min": 0, "max": 999999999999, "step": 0.01}, {"key": "tentativa", "label": "¿Fue tentativa?", "type": "text", "group": "delito1", "required": false, "options": ["Sí", "No"]}, {"key": "fuero", "label": "Fuero / leyes especiales", "type": "text", "group": "delito1", "required": false}, {"key": "delito_general", "label": "Delito general", "type": "text", "group": "delito1", "required": false}, {"key": "delito_especifico", "label": "Delito específico", "type": "text", "group": "delito1", "required": false}, {"key": "subtipo", "label": "Subtipo de delito", "type": "text", "group": "delito1", "required": false}, {"key": "tentativa_2", "label": "¿Fue tentativa?", "type": "text", "group": "delito2", "required": false, "options": ["Sí", "No"]}, {"key": "fuero_2", "label": "Fuero / leyes especiales", "type": "text", "group": "delito2", "required": false}, {"key": "delito_general_2", "label": "Delito general", "type": "text", "group": "delito2", "required": false}, {"key": "delito_especifico_2", "label": "Delito específico", "type": "text", "group": "delito2", "required": false}, {"key": "subtipo_2", "label": "Subtipo de delito", "type": "text", "group": "delito2", "required": false}]$local$::jsonb;end if;
 if spec is null then$inject$);
 execute d;
end $patch$;
notify pgrst,'reload schema';
commit;
