(() => {
 const trigger=document.getElementById('logoutBtn');if(!trigger)return;
 const box=document.createElement('div');box.className='account-controls';trigger.before(box);box.append(trigger);trigger.type='button';trigger.title='Opciones de mi cuenta';trigger.setAttribute('aria-haspopup','menu');trigger.setAttribute('aria-expanded','false');trigger.setAttribute('aria-controls','accountMenu');
 const menu=document.createElement('div');menu.id='accountMenu';menu.className='account-menu';menu.hidden=true;menu.setAttribute('role','menu');menu.innerHTML='<button type="button" role="menuitem" id="changeOwnPassword">Cambiar contraseña</button><button type="button" role="menuitem" id="accountSignOut">Cerrar sesión</button>';box.append(menu);
 const closeMenu=()=>{menu.hidden=true;trigger.setAttribute('aria-expanded','false');};trigger.onclick=()=>{menu.hidden=!menu.hidden;trigger.setAttribute('aria-expanded',String(!menu.hidden));if(!menu.hidden)menu.querySelector('button').focus();};
 document.addEventListener('click',e=>{if(!box.contains(e.target))closeMenu();});box.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();trigger.focus();}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const buttons=[...menu.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);buttons[(index+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length].focus();}});
 const dialog=document.createElement('dialog');dialog.className='record-dialog';dialog.setAttribute('aria-labelledby','ownPasswordTitle');dialog.innerHTML='<form class="record-modal-card account-password-form"><h2 id="ownPasswordTitle">Cambiar mi contraseña</h2><p>Actualice la contraseña de su propia cuenta. Use al menos 8 caracteres.</p><label>Nueva contraseña<input name="newPassword" type="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><label>Confirmar nueva contraseña<input name="confirmPassword" type="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><p role="status" data-password-status></p><div class="form-actions"><button type="button" class="secondary" data-password-close>Cancelar</button><button type="submit" class="primary">Guardar contraseña</button></div></form>';document.body.append(dialog);
 const form=dialog.querySelector('form'),message=dialog.querySelector('[data-password-status]'),submit=form.querySelector('[type=submit]'),cancel=form.querySelector('[data-password-close]');let busy=false;
 document.getElementById('changeOwnPassword').onclick=()=>{closeMenu();if(!currentProfile?.activo)return;form.reset();message.textContent='';submit.disabled=false;cancel.textContent='Cancelar';dialog.showModal();};cancel.onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>form.reset());
 form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!currentProfile?.activo||!form.reportValidity())return;const password=form.elements.newPassword.value;if(password!==form.elements.confirmPassword.value){message.textContent='Las contraseñas no coinciden.';return;}const actor=currentProfile.id;busy=true;submit.disabled=cancel.disabled=true;message.textContent='Actualizando contraseña…';
  try{const {data:session,error:sessionError}=await supabaseClient.auth.getUser();if(sessionError||session.user?.id!==actor)throw new Error('La sesión cambió. Cierre este formulario e inicie sesión nuevamente.');const {data,error}=await supabaseClient.auth.updateUser({password});if(error)throw error;if(data.user?.id!==actor)throw new Error('No se recibió confirmación del cambio.');form.reset();message.textContent='Contraseña actualizada correctamente. Úsela en su próximo ingreso.';cancel.textContent='Cerrar';}
  catch(error){const messages={same_password:'La nueva contraseña debe ser diferente de la actual.',weak_password:'La contraseña no cumple los requisitos de seguridad. Elija una más segura.',reauthentication_needed:'Por seguridad, cierre sesión e ingrese nuevamente antes de cambiar su contraseña.',over_request_rate_limit:'Demasiados intentos. Espere unos minutos antes de reintentar.'};message.textContent=messages[error.code]||'No se confirmó el cambio. Compruebe su conexión y vuelva a intentarlo.';}
  finally{busy=false;submit.disabled=false;cancel.disabled=false;}
 });
 document.getElementById('accountSignOut').onclick=async()=>{closeMenu();const b=document.getElementById('accountSignOut');b.disabled=true;try{await window.signOutAccount();}finally{b.disabled=false;}};
})();
