(() => {
 const host=document.querySelector('#consultaRecordsView .records-toolbar');if(!host)return;
 const button=document.createElement('button');button.className='secondary';button.type='button';button.textContent='Declarar sin producción';button.hidden=true;host.prepend(button);
 const dialog=document.createElement('dialog');dialog.className='seg-dialog';dialog.innerHTML='<form><h3>Declaración diaria de mi dependencia</h3><p data-unit></p><p>Use esta opción sólo si no hubo producción operativa en el día elegido. Quedará constancia de su usuario y de la hora de declaración.</p><label>Fecha<input type="date" name="date" required></label><p data-message role="status"></p><div><button type="button" class="secondary" data-close>Cerrar</button><button type="button" class="secondary" data-withdraw>Retirar declaración</button><button class="primary" type="submit">Declarar sin producción</button></div></form>';document.body.append(dialog);
 const $=q=>dialog.querySelector(q),today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),identity=()=>JSON.stringify([currentProfile?.id,currentProfile?.unidad,currentProfile?.rol,currentProfile?.activo]);let busy=false,owner='';
 const eligible=()=>currentProfile?.activo&&['estadistico_division','estadistico_depitptim'].includes(currentProfile.rol);
 button.addEventListener('click',()=>{if(!eligible())return;owner=identity();$('[data-unit]').textContent=currentProfile.unidad;$('[name=date]').value=today();$('[name=date]').max=today();$('[data-message]').textContent='';dialog.showModal();});
 async function save(value){if(busy||!eligible()||owner!==identity()||!$('form').reportValidity())return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);const who=identity();try{const {error}=await supabaseClient.rpc('declarar_seguimiento',{p_fecha:$('[name=date]').value,p_unidad:currentProfile.unidad,p_sin_produccion:value});if(who!==identity())return;if(error)throw error;$('[data-message]').textContent=value?'Declaración sin producción guardada. Dirección y Jefatura podrán verla en Seguimiento.':'Declaración retirada; queda constancia en el historial.';}catch(e){if(who===identity())$('[data-message]').textContent=e.message||'No se pudo guardar.';}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 $('form').addEventListener('submit',e=>{e.preventDefault();save(true);});$('[data-withdraw]').addEventListener('click',()=>save(false));$('[data-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 window.updateDeclaracionDiaria=()=>{button.hidden=!eligible();};window.resetDeclaracionDiaria=()=>{dialog.close();owner='';$('[data-unit]').textContent='';$('[data-message]').textContent='';button.hidden=true;};window.updateDeclaracionDiaria();
})();
