(() => {
 const sidebar=document.querySelector('.sidebar'),menu=document.querySelector('.menu'),login=document.getElementById('loginScreen');
 const nav=document.createElement('nav');nav.className='mobile-bottom-nav';nav.setAttribute('aria-label','Navegación rápida');
 const icons={dashboard:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',records:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'};
 for(const [name,label,view] of [['dashboard','Dashboard','generalDashboardView'],['records','Registros','consultaRecordsView'],['menu','Menú',null]]){const b=document.createElement('button');b.type='button';b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">'+icons[name]+'</svg><span>'+label+'</span>';b.dataset.target=view||'';b.onclick=()=>view?sidebar.querySelector('[data-view="'+view+'"]').click():menu.click();nav.append(b);}
 document.body.append(nav);
 const sync=()=>{nav.hidden=!login.classList.contains('hidden');for(const b of nav.children){const selected=b.dataset.target&&document.getElementById(b.dataset.target)?.classList.contains('active');if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}};
 new MutationObserver(sync).observe(login,{attributes:true,attributeFilter:['class']});document.querySelectorAll('.view').forEach(v=>new MutationObserver(sync).observe(v,{attributes:true,attributeFilter:['class']}));sync();
 for(const selector of ['.dash-filter-panel','.records-filter-panel']){const form=document.querySelector(selector);if(!form)continue;const b=document.createElement('button');b.type='button';b.className='mobile-filter-toggle';b.textContent='Filtros de consulta';b.setAttribute('aria-expanded','true');b.onclick=()=>{const closed=form.classList.toggle('mobile-filters-closed');b.setAttribute('aria-expanded',String(!closed));b.textContent=closed?'Mostrar filtros de consulta':'Ocultar filtros de consulta';};form.before(b);}
 const card=document.querySelector('.dash-map-card');if(card){const b=document.createElement('button');b.type='button';b.className='map-expand';b.textContent='⛶ Ampliar mapa';b.setAttribute('aria-expanded','false');const toggle=()=>{const expanded=card.classList.toggle('map-expanded');b.textContent=expanded?'✕ Cerrar mapa ampliado':'⛶ Ampliar mapa';b.setAttribute('aria-expanded',String(expanded));window.dispatchEvent(new Event('resize'));};b.onclick=toggle;card.querySelector('[data-map-hover]').before(b);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&card.classList.contains('map-expanded'))toggle();});}
})();