// Panorama completo. Las mismas consultas y políticas de acceso que Registros.
(() => {
 const Q=window.ConsultaModelo,root=document.getElementById('generalDashboardView');if(!Q||!root)return;
 const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!=null)x.textContent=text;if(cls)x.className=cls;return x;};
 const format=n=>new Intl.NumberFormat('es-PE',{maximumFractionDigits:2}).format(n);
 const identity=()=>JSON.stringify([currentProfile?.id,currentProfile?.rol,currentProfile?.unidad,currentProfile?.activo]);
 const icons={people:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5v2"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',box:'<path d="m3 7 9-4 9 4v10l-9 4-9-4zM3 7l9 4 9-4M12 11v10"/>',money:'<rect x="2" y="5" width="20" height="14" rx="3"/><circle cx="12" cy="12" r="3"/><path d="M5 9v6M19 9v6"/>',car:'<path d="m4 9 2-5h12l2 5M3 9h18v10H3zM6 19v2m12-2v2M6 13h2m8 0h2"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4"/>'};
 Object.assign(icons,{detenidos:'<circle cx="6" cy="15" r="4"/><circle cx="18" cy="15" r="4"/><path d="M3 12V7a3 3 0 0 1 6 0v5m6 0V7a3 3 0 0 1 6 0v5M10 15h4"/>',organizacion:'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5H5v5m7-5h7v5"/>',migraciones:'<path d="m2 14 8-3V4a2 2 0 0 1 4 0v7l8 3v3l-8-2v5l3 2H7l3-2v-5l-8 2z"/>'});
 const icon=c=>icons[c.id]||icons[c.id==='dinero'?'money':['celulares','chips'].includes(c.id)?'phone':c.table==='intervencion_vehiculos'?'car':c.table==='intervenciones'?'shield':['rq','personas_ubicadas','desaparecidos'].includes(c.id)?'search':['detenidos','victimas','menores','prostitucion','migraciones','expulsados','banda','organizacion'].includes(c.id)?'people':'box'];
 const cats=Q.categories().filter(c=>c.id!=='drogas');
 const featured=['detenidos','rq','banda','organizacion','victimas','celulares','migraciones','personas_ubicadas'];
 const section=el('section',null,'production-overview');section.id='productionOverview';section.setAttribute('aria-label','Resumen de toda la producción');
 section.innerHTML='<header class="production-heading"><div><span class="dash-eyebrow">VISIÓN INTEGRAL</span><h2>La producción, en una sola mirada</h2><p>Todas las categorías · todo el historial autorizado</p></div><button type="button" class="secondary" data-summary-refresh>↻ Actualizar resumen</button></header><div class="production-stage"><button class="production-core" type="button" data-core><span class="production-core-label">ACTIVIDAD OPERATIVA</span><span class="production-map-ring"><img class="production-peru" src="frontend/assets/maps/peru-overview.svg" alt="Mapa del Perú" width="250" height="340"><img class="production-seal" src="frontend/assets/logo-diriptim.png" alt="Escudo DIRITPTIM" width="62" height="62"></span><strong data-core-count>—</strong><span>Operativos</span><small data-core-mega>Consultando megaoperativos…</small><span class="production-core-link">Explorar producción ↗</span></button><div class="production-featured" data-summary-featured></div></div><div class="production-divider"><span>OTROS RESULTADOS Y BIENES</span><span>Seleccione un indicador para analizarlo ↗</span></div><div class="production-all" data-summary-all></div><p class="production-status" role="status" data-summary-status>Consultando los indicadores autorizados…</p><p class="production-note">Este panorama es independiente de los filtros de abajo. Cada indicador conserva su unidad de medida; no se suman categorías entre sí. Incluye los registros guardados y los pendientes de completar.</p>';
 root.querySelector('.dash-section-nav').before(section);
 const $=s=>section.querySelector(s),cards=new Map();let epoch=0,whoLoaded='',pending=false;
 const open=id=>{const form=root.querySelector('.dash-filter-panel'),select=form.querySelector('[name="category"]');form.classList.remove('mobile-filters-closed');const toggle=form.previousElementSibling;if(toggle?.classList.contains('mobile-filter-toggle')){toggle.setAttribute('aria-expanded','true');toggle.textContent='Ocultar filtros de consulta';}form.reset();select.value=id;select.dispatchEvent(new Event('change',{bubbles:true}));form.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
 $('[data-core]').onclick=()=>open('operativos');
 for(const c of cats.filter(c=>c.id!=='operativos')){const b=el('button',null,'production-tile');b.type='button';b.dataset.category=c.id;b.innerHTML='<span class="production-tile-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">'+icon(c)+'</svg></span>';b.append(el('span',c.id==='victimas'?'Víctimas de trata':c.title,'production-tile-title'),el('strong','—','production-tile-value'),el('small','Consultando…','production-tile-detail'));b.onclick=()=>open(c.id);b.disabled=true;cards.set(c.id,b);$(featured.includes(c.id)?'[data-summary-featured]':'[data-summary-all]').append(b);}
 const descriptions={detenidos:'Personas detenidas por diversos delitos.',rq:'Personas capturadas por requisitoria judicial.',banda:'Bandas criminales registradas',organizacion:'Organizaciones criminales registradas',victimas:'Víctimas y presuntas víctimas de trata de personas.',celulares:'Equipos celulares registrados en las intervenciones.',migraciones:'Personas intervenidas por la Ley de Migraciones.',personas_ubicadas:'Personas ubicadas por las dependencias del ámbito autorizado.'};
 const describe=(c,m)=>descriptions[c.id]?(descriptions[c.id]+(c.table==='intervencion_grupos'?' · '+m.detail.replace('grupos · ',''):c.id==='celulares'?' '+m.detail.replace(/^unidades · /,''): '')):m.detail;
 const number=v=>{if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;};
 function metric(records,c){const rows=records.map(r=>Q.normalize(r,c,new Map())),sum=k=>rows.reduce((n,r)=>n+(number(r.data[k])??0),0);let value=format(rows.length),detail='registros';
  if(c.table==='intervencion_grupos')detail='grupos · '+format(sum('integrantes'))+' integrantes';
  if(c.table==='intervenciones')detail='operativos registrados';
  if(['celulares','chips'].includes(c.id)||c.table==='intervencion_drogas'||(c.table==='intervencion_materiales'&&c.fields.some(f=>f.key==='cantidad'))){const missing=rows.filter(r=>number(r.data.cantidad)===null).length;value=format(sum('cantidad'));detail=(c.table==='intervencion_drogas'?(c.type.startsWith('kg_')?'kg':'envoltorios'):'unidades')+' · '+format(rows.length)+' registros'+(missing?' · '+missing+' sin cantidad':'');}
  if(c.id==='dinero'){value='S/ '+format(sum('soles'));detail='USD '+format(sum('dolares'))+' · EUR '+format(sum('euros'));}
  if(c.id==='victimas'){const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();const rescued=rows.filter(r=>norm(r.data.situacion).includes('RESCATAD')).length,presumed=rows.filter(r=>norm(r.data.situacion).includes('PRESUNTA')).length;detail=rescued+' rescatadas · '+presumed+' presuntas'+(rows.length-rescued-presumed?' · '+(rows.length-rescued-presumed)+' sin clasificar':'');}
  if(!rows.length)detail='Sin registros';return {value,detail};
 }
 function clear(){for(const b of cards.values()){b.querySelector('strong').textContent='—';b.querySelector('small').textContent='Consultando…';b.disabled=true;b.classList.remove('production-failed');}$('[data-core-count]').textContent='—';$('[data-core-mega]').textContent='Consultando megaoperativos…';$('[data-core]').disabled=true;}
 async function load(force=false,quiet=false){const who=identity();if(!currentProfile?.activo)return;if(!force&&whoLoaded===who)return;const token=++epoch;whoLoaded=who;pending=true;if(!quiet)clear();section.setAttribute('aria-busy','true');if(!quiet)$('[data-summary-status]').textContent='Consultando todas las categorías de su ámbito…';const alive=()=>token===epoch&&who===identity()&&currentProfile?.activo;
  const tables=[...new Set(cats.map(c=>c.table))];let at=0,failures=0;
  async function worker(){while(at<tables.length&&alive()){const table=tables[at++],members=cats.filter(c=>c.table===table),example=members[0];try{const records=await Q.readAll(supabaseClient,{table,select:example.select},alive);if(!alive())return;for(const c of members){const relevant=c.type?records.filter(r=>r.tipo===c.type):records,m=metric(relevant,c);if(c.id==='operativos'){$('[data-core-count]').textContent=m.value;$('[data-core]').disabled=false;}else{const b=cards.get(c.id);b.querySelector('strong').textContent=m.value;b.querySelector('small').textContent=describe(c,m);b.disabled=false;b.classList.remove('production-failed');}if(c.id==='megaoperativos')$('[data-core-mega]').textContent=m.value+' megaoperativos · categoría separada';}}catch(e){if(!alive())return;failures++;for(const c of members){if(c.id==='operativos'){$('[data-core-count]').textContent='—';$('[data-core]').disabled=true;}const b=cards.get(c.id);if(b){b.querySelector('strong').textContent='—';b.disabled=true;b.querySelector('small').textContent='No disponible · reintentando automáticamente';b.classList.add('production-failed');}if(c.id==='megaoperativos')$('[data-core-mega]').textContent='Megaoperativos: consulta no disponible';}}}}
  await Promise.all([worker(),worker(),worker()]);if(!alive())return;pending=false;section.removeAttribute('aria-busy');$('[data-summary-status]').textContent=failures?'Algunas categorías no pudieron consultarse. Sus valores se muestran como —, no como cero.':'Actualizado '+new Intl.DateTimeFormat('es-PE',{dateStyle:'short',timeStyle:'short',timeZone:'America/Lima'}).format(new Date())+' · hora de Lima · '+nombrePerfil(currentProfile.rol)+' · '+(currentProfile.unidad||'');if(failures)whoLoaded='';
 }
 window.refreshOverviewAutomatically=()=>load(true,true);
 window.loadProductionOverview=()=>load(false);window.resetProductionOverview=()=>{epoch++;whoLoaded='';pending=false;clear();section.removeAttribute('aria-busy');$('[data-summary-status]').textContent='Inicie sesión para consultar su ámbito autorizado.';};
 $('[data-summary-refresh]').onclick=()=>load(true);root.querySelector('[data-refresh]').addEventListener('click',()=>load(true));
 if(currentProfile?.activo&&root.classList.contains('active'))load();
})();