(() => {
 const root=document.getElementById('seguimientoView'),make=(t,text,cls)=>{const n=document.createElement(t);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 const day=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(v?new Date(v):new Date());
 const stamp=v=>v?new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'Sin ingresos';
 const allowed=()=>currentProfile?.activo&&['administrador','estadistico_direccion','estadistico_jefatura'].includes(currentProfile.rol);
 const identity=()=>JSON.stringify([currentProfile?.id,currentProfile?.rol,currentProfile?.unidad,currentProfile?.activo]);
 const state=r=>Number(r.operativos)+Number(r.detalles)>0?'reported':r.sin_produccion?'zero':'pending',labels={reported:'Con registros',zero:'Sin producción',pending:'Pendiente'};
 let rows=[],turn=0,loadedDate='',page=1,pending=null,busy=false;
 root.innerHTML=`<header class="seg-title"><div><h2>Seguimiento de registro diario</h2><p>Conoce qué divisiones y DEPITPTIM informaron y cuáles tienen información pendiente.</p></div><time data-date-title></time></header>
 <form class="seg-filters"><label>Fecha<input name="date" type="date" required></label><div class="seg-quick"><button type="button" class="secondary" data-today>Hoy</button><button type="button" class="secondary" data-yesterday>Ayer</button></div><label>Departamento<select name="department"><option value="">Todos los departamentos</option></select></label><label>Estado<select name="status"><option value="">Todos</option><option value="reported">Con registros</option><option value="zero">Sin producción</option><option value="pending">Pendiente</option><option value="late">Ingreso tardío</option></select></label><button class="primary">↻ Actualizar</button></form>
 <p class="seg-message" role="status" aria-live="polite"></p><div class="seg-metrics"></div>
 <div class="seg-chart-grid"><section class="seg-panel"><h3>Estado de reporte del día</h3><div class="seg-donut-layout"><div class="seg-donut" role="img"><div><strong data-total>—</strong><span>dependencias</span></div></div><div class="seg-legend"></div></div></section><section class="seg-panel"><h3>Reporte por departamento</h3><p class="seg-subtitle">Con registros o declaración sin producción · porcentaje de dependencias</p><div class="seg-bars-scroll"><div class="seg-bars"></div></div></section></div>
 <div class="seg-detail-grid"><section class="seg-panel seg-table-panel"><header><div><h3>Dependencias / último ingreso</h3><p class="seg-subtitle">Estadísticos asignados actualmente a cada unidad</p></div><input name="search" type="search" aria-label="Buscar dependencia o estadístico" placeholder="Buscar dependencia o estadístico…"></header><div class="seg-table-scroll"><table><thead><tr><th>Dependencia / estadístico</th><th>Departamento</th><th>Estado del día</th><th>Último ingreso</th><th>Días desde ingreso</th><th>Acción</th></tr></thead><tbody></tbody></table></div><footer><span data-count></span><div class="seg-pagination"><button type="button" class="secondary" data-prev aria-label="Página anterior">‹</button><span data-page></span><button type="button" class="secondary" data-next aria-label="Página siguiente">›</button></div></footer></section>
 <aside class="seg-side"><section class="seg-alert-panel"><header><h3>⚠ Alertas</h3><button type="button" data-pending>Ver pendientes</button></header><div data-alerts></div></section><section class="seg-panel seg-recent"><header><h3>Últimos ingresos</h3><span>En la fecha elegida</span></header><div data-recent></div></section></aside></div>
 <details class="seg-help"><summary>Cómo se calcula el seguimiento</summary><p>Se usa la fecha del operativo o de la denuncia de desaparición y los horarios reales de creación en Perú. «Con registros» incluye borradores y no certifica un parte completo. «Sin producción» es una declaración expresa. Hoy permanece abierto hasta las 23:59.</p><p>Un ingreso tardío se guardó después del día del operativo o de la denuncia. «Días desde ingreso» mide días calendario desde la última alta hasta el día consultado; no equivale a días de incumplimiento ni cuenta declaraciones o ediciones. Las fichas independientes de enrolamiento no se incluyen.</p><p>La cobertura corresponde a las dependencias del catálogo autorizadas. Si se registra producción después de declarar cero, prevalecen los registros y se conserva la declaración histórica.</p><small data-scope></small></details>
 <dialog class="seg-detail-dialog"><header><h3>Detalle del seguimiento</h3><button type="button" data-close-detail aria-label="Cerrar detalle">×</button></header><div data-detail></div></dialog>
 <dialog class="seg-dialog"><form method="dialog"><h3 data-dialog-title></h3><p data-dialog-description></p><p data-dialog-error role="alert"></p><div><button class="secondary" value="cancel">Cancelar</button><button type="button" class="primary" data-confirm>Confirmar declaración</button></div></form></dialog>`;
 const $=q=>root.querySelector(q),date=$('[name=date]');date.value=day();date.max=day();
 const late=r=>Number(r.tardios)>0||(state(r)==='zero'&&r.declarado_en&&day(r.declarado_en)>loadedDate);
 const base=()=>rows.filter(r=>!$('[name=department]').value||(r.departamento||'OTROS')===$('[name=department]').value),pct=(n,t)=>t?Math.round(100*n/t):0;
 function clear(){rows=[];for(const q of ['tbody','.seg-metrics','.seg-bars','.seg-legend','[data-alerts]','[data-recent]','[data-detail]'])$(q).replaceChildren();$('[data-total]').textContent='—';$('[data-count]').textContent='';$('[data-page]').textContent='';$('.seg-donut').style.background='#e9f1eb';$('.seg-donut').setAttribute('aria-label','Sin consulta');}
 async function load(){const token=++turn,who=identity(),chosen=date.value;clear();loadedDate='';page=1;date.max=day();root.setAttribute('aria-busy','true');$('.seg-message').textContent='Consultando seguimiento…';const alive=()=>token===turn&&who===identity()&&allowed();
 try{if(!allowed())throw Error('Este panel está reservado para Administración, Dirección y Jefatura.');if(!date.checkValidity())throw Error('Seleccione una fecha válida, de hoy o anterior.');const {data,error}=await supabaseClient.rpc('consultar_seguimiento',{p_fecha:chosen});if(!alive())return;if(error)throw error;rows=data||[];loadedDate=chosen;
 const old=$('[name=department]').value;$('[name=department]').replaceChildren(new Option('Todos los departamentos',''),...[...new Set(rows.map(r=>r.departamento||'OTROS'))].sort((a,b)=>a.localeCompare(b,'es')).map(d=>new Option(d,d)));$('[name=department]').value=old;if($('[name=department]').selectedIndex<0)$('[name=department]').value='';
 $('[data-date-title]').textContent=new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',dateStyle:'full'}).format(new Date(chosen+'T12:00:00Z'));$('.seg-message').textContent=chosen===day()?'Día en curso · puede seguir ingresando información hasta las 23:59.':'Consulta histórica · las incorporaciones posteriores se identifican como tardías.';$('[data-scope]').textContent=`${nombrePerfil(currentProfile.rol)} · ${currentProfile.unidad}`;render();
 }catch(e){if(token===turn)$('.seg-message').textContent=`No se pudo consultar. ${e.message||'Intente nuevamente.'}`;}finally{if(token===turn)root.removeAttribute('aria-busy');}}
 function statusFilter(value){$('[name=status]').value=value;page=1;table();}
 const icons={users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m1 3a5 5 0 0 1 3 4v3"/>',check:'<circle cx="12" cy="12" r="9"/><path d="m7 12 3 3 7-7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',bars:'<path d="M5 20v-5m7 5V9m7 11V3"/>'};
 function render(){const selected=base(),expected=selected.filter(r=>r.catalogada),c={reported:0,zero:0,pending:0};expected.forEach(r=>c[state(r)]++);const total=expected.length,done=c.reported+c.zero;
 $('.seg-metrics').replaceChildren();for(const [symbol,title,n,note,cls,filter]of [['users','Total de dependencias',total,'En su ámbito de consulta','total',''],['check','Informaron',done,`${c.reported} con registros · ${c.zero} sin producción`,'reported',''],['clock','Pendientes',c.pending,`${pct(c.pending,total)}% sin información del día`,'pending','pending'],['bars','Cobertura de reporte',pct(done,total)+'%','Con registros o declaración sin producción','coverage','']]){const card=make('button',null,`seg-metric ${cls}`);card.type='button';const icon=make('span',null,'seg-icon');icon.innerHTML=`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[symbol]}</svg>`;const text=make('div');text.append(make('span',title),make('strong',n),make('small',note));card.append(icon,text);card.addEventListener('click',()=>statusFilter(filter));$('.seg-metrics').append(card);}
 const colors={reported:'#18b879',zero:'#9bd779',pending:'#e75b67'},p1=total?c.reported/total*100:0,p2=total?done/total*100:0;$('.seg-donut').style.background=total?`conic-gradient(${colors.reported} 0 ${p1}%,${colors.zero} ${p1}% ${p2}%,${colors.pending} ${p2}% 100%)`:'#e9f1eb';$('.seg-donut').setAttribute('aria-label',`${c.reported} con registros, ${c.zero} sin producción, ${c.pending} pendientes`);$('[data-total]').textContent=total;$('.seg-legend').replaceChildren();for(const k of ['reported','zero','pending']){const b=make('button');b.type='button';const dot=make('i');dot.style.background=colors[k];b.append(dot,make('span',labels[k]),make('strong',`${c[k]} (${pct(c[k],total)}%)`));b.addEventListener('click',()=>statusFilter(k));$('.seg-legend').append(b);}
 const groups=new Map();for(const r of expected){const k=r.departamento||'OTROS',g=groups.get(k)||{total:0,done:0};g.total++;if(state(r)!=='pending')g.done++;groups.set(k,g);}$('.seg-bars').replaceChildren();for(const [name,g]of [...groups].sort((a,b)=>a[0].localeCompare(b[0],'es'))){const value=pct(g.done,g.total),b=make('button',null,'seg-bar');b.type='button';b.title=`${name}: ${g.done} de ${g.total} dependencias (${value}%)`;b.setAttribute('aria-label',b.title);const plot=make('span',null,'seg-bar-plot'),fill=make('i');fill.style.height=value+'%';plot.append(fill,make('strong',value+'%'));b.append(plot,make('span',name,'seg-bar-label'));b.addEventListener('click',()=>{$('[name=department]').value=name;page=1;render();});$('.seg-bars').append(b);}
 if(!groups.size)$('.seg-bars').append(make('p','Sin dependencias para esta selección.','seg-empty'));
 $('[data-alerts]').replaceChildren();for(const [text,cls,filter]of [[`${c.pending} dependencias pendientes de informar`,'pending','pending'],[`${expected.filter(late).length} con ingresos o declaraciones tardías`,'late','late'],[`${expected.filter(r=>!r.responsables?.length).length} sin estadístico activo asignado`,'unassigned',null]]){const alert=make(filter?'button':'div',text,`seg-alert ${cls}`);if(filter){alert.type='button';alert.addEventListener('click',()=>statusFilter(filter));}$('[data-alerts]').append(alert);}
 const recent=selected.filter(r=>r.ultimo_ingreso_del_dia).sort((a,b)=>b.ultimo_ingreso_del_dia.localeCompare(a.ultimo_ingreso_del_dia)).slice(0,5);$('[data-recent]').replaceChildren();for(const r of recent){const b=make('button',null,'seg-recent-item');b.type='button';const t=new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(r.ultimo_ingreso_del_dia)),d=make('div');d.append(make('strong',r.ultimo_usuario_del_dia||'Usuario registrador'),make('span',r.unidad));b.append(make('time',t),d);b.addEventListener('click',()=>detail(r));$('[data-recent]').append(b);}if(!recent.length)$('[data-recent]').append(make('p','No hay ingresos en la fecha elegida.','seg-empty'));table();}
 function table(){const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),term=norm($('[name=search]').value),filter=$('[name=status]').value,shown=base().filter(r=>(!filter||(filter==='late'?late(r):state(r)===filter))&&norm([r.unidad,...(r.responsables||[])].join(' ')).includes(term));const pages=Math.max(1,Math.ceil(shown.length/8));page=Math.min(Math.max(1,page),pages);const start=(page-1)*8;const body=$('tbody');body.replaceChildren();
 for(const r of shown.slice(start,start+8)){const tr=make('tr'),unit=make('td'),status=make('td'),action=make('td');unit.append(make('strong',r.unidad),make('small',(r.responsables||[]).join(' · ')||'Sin estadístico activo asignado'));if(!r.catalogada)unit.append(make('small','Unidad adicional · fuera del porcentaje'));status.append(make('span',labels[state(r)],`seg-pill ${state(r)}`));if(late(r))status.append(make('small','Ingreso tardío','seg-late'));const b=make('button','Ver detalle','seg-detail-button');b.type='button';b.addEventListener('click',()=>detail(r));action.append(b);tr.append(unit,make('td',r.departamento||'OTROS'),status,make('td',stamp(r.ultimo_registro)),make('td',r.dias_desde_ingreso??'—'),action);body.append(tr);}
 if(!shown.length){const tr=make('tr'),td=make('td','No hay dependencias para esta selección.','seg-empty');td.colSpan=6;tr.append(td);body.append(tr);}$('[data-count]').textContent=`Mostrando ${shown.length?start+1:0}–${Math.min(start+8,shown.length)} de ${shown.length} dependencias`;$('[data-page]').textContent=`${page} / ${pages}`;$('[data-prev]').disabled=page<=1;$('[data-next]').disabled=page>=pages;}
 function detail(r){const box=$('[data-detail]');box.replaceChildren();box.append(make('h4',r.unidad),make('p',`${loadedDate} · ${labels[state(r)]}`),make('p',`Estadístico asignado: ${(r.responsables||[]).join(' · ')||'Sin cuenta activa'}`));const dl=make('dl');for(const [k,v]of [['Operativos del día',r.operativos],['Detalles del día',r.detalles],['Ingresos tardíos',r.tardios],['Altas realizadas en esta fecha',r.ingresados_ese_dia],['De operativos de días anteriores',r.de_fechas_anteriores],['Último ingreso del parte',stamp(r.ultimo_ingreso)],['Último registrador del parte',r.ultimo_usuario||'—']])dl.append(make('dt',k),make('dd',v));box.append(dl);if(r.sin_produccion)box.append(make('p',`Declaración sin producción: ${stamp(r.declarado_en)} · ${r.declarado_por||'Usuario declarante'}`));if(state(r)==='reported'&&r.sin_produccion)box.append(make('p','Los registros actuales prevalecen sobre la declaración anterior.'));
 if(r.catalogada&&(state(r)==='pending'||(state(r)==='zero'&&r.puede_anular))){const value=state(r)==='pending',b=make('button',value?'Declarar sin producción':'Retirar declaración','primary');b.type='button';b.addEventListener('click',()=>{$('.seg-detail-dialog').close();declare(r,value);});box.append(b);}$('.seg-detail-dialog').showModal();}
 function declare(row,value){if(busy)return;pending={row,value,date:loadedDate,who:identity()};$('[data-dialog-title]').textContent=value?'Declarar día sin producción':'Retirar declaración';$('[data-dialog-description]').textContent=`${row.unidad} · ${loadedDate}. ${value?'Confirma que no hubo producción operativa en esta dependencia durante ese día.':'Se conservará constancia del retiro y de su autor.'}`;$('[data-dialog-error]').textContent='';$('[data-confirm]').textContent=value?'Confirmar sin producción':'Retirar declaración';$('.seg-dialog').showModal();}
 $('[data-confirm]').addEventListener('click',async()=>{if(!pending||busy)return;const p=pending;if(p.who!==identity()||!allowed()){reset();return;}busy=true;$('[data-confirm]').disabled=true;try{const {error}=await supabaseClient.rpc('declarar_seguimiento',{p_fecha:p.date,p_unidad:p.row.unidad,p_sin_produccion:p.value});if(p.who!==identity())return;if(error)throw error;$('.seg-dialog').close();pending=null;await load();}catch(e){if(p.who===identity())$('[data-dialog-error]').textContent=e.message||'No se pudo guardar.';}finally{busy=false;$('[data-confirm]').disabled=false;}});
 $('.seg-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('.seg-dialog form').addEventListener('submit',e=>{if(busy)e.preventDefault();});$('[data-close-detail]').addEventListener('click',()=>$('.seg-detail-dialog').close());
 $('form.seg-filters').addEventListener('submit',e=>{e.preventDefault();load();});date.addEventListener('change',load);$('[name=status]').addEventListener('change',()=>{page=1;table();});$('[name=search]').addEventListener('input',()=>{page=1;table();});$('[name=department]').addEventListener('change',()=>{page=1;render();});$('[data-today]').addEventListener('click',()=>{date.value=day();load();});$('[data-yesterday]').addEventListener('click',()=>{const d=new Date(day()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);date.value=d.toISOString().slice(0,10);load();});$('[data-prev]').addEventListener('click',()=>{page--;table();});$('[data-next]').addEventListener('click',()=>{page++;table();});$('[data-pending]').addEventListener('click',()=>statusFilter('pending'));
 function reset(){turn++;clear();loadedDate='';pending=null;$('.seg-dialog').close();$('.seg-detail-dialog').close();date.value=day();$('[name=status]').value='';$('[name=search]').value='';$('[name=department]').replaceChildren(new Option('Todos los departamentos',''));$('.seg-message').textContent='';$('[data-scope]').textContent='';$('[data-date-title]').textContent='';root.removeAttribute('aria-busy');}
 window.loadSeguimiento=load;window.resetSeguimiento=reset;
})();
